name: Rubrik On-Demand Backup
description: Trigger and monitor an on-demand Rubrik backup for a GitHub repository, failing the workflow if the backup does not succeed.
author: Mike Preston

inputs:
  rsc-uri:
    description: Rubrik Security Cloud base URL (e.g. https://<tenant>)
    required: true
  client-id:
    description: OAuth client ID
    required: true
  client-secret:
    description: OAuth client secret
    required: true
  repository:
    description: GitHub repository name (e.g. owner/repo)
    required: true
  sla-name:
    description: Name of the SLA Domain to use for the backup
    required: true
  wait:
    description: Whether or not to wait for backup completion before finishing the action
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Install requests
      run: python -m pip install --upgrade pip requests
      shell: bash

    - name: Run Rubrik On-Demand Backup
      run: python ${{ github.action_path }}/scripts/rubrik_backup.py
      shell: bash
      env:
        RUBRIK_RSC_URI: ${{ inputs.rsc-uri }}
        RUBRIK_CLIENT_ID: ${{ inputs.client-id }}
        RUBRIK_CLIENT_SECRET: ${{ inputs.client-secret }}
        GITHUB_REPO_NAME: ${{ inputs.repository }}
        RUBRIK_SLA_DOMAIN_NAME: ${{ inputs.sla-name }}
        WAIT_FOR_COMPLETION: ${{ inputs.wait }}